import 'server-only'

import { createClient } from '@/lib/supabase/server'
import type { Tables } from '@/lib/supabase/database.types'

// Generated by `npm run db:types`. View columns are nullable because Postgres
// cannot prove otherwise through a view.
export type ConnectionOverview = Tables<'connection_overview'>
export type Message = Tables<'messages'>

/**
 * Everything the connections screen needs, in one round trip: the other
 * person's card, the last message, and an unread count per conversation.
 *
 * Fetching connections and then looping for profiles, last messages and counts
 * would be four queries per row. The connection_overview view does it with
 * LATERALs instead — see supabase/migrations/0002_views.sql.
 */
export async function getConnections(): Promise<ConnectionOverview[]> {
  const supabase = await createClient()

  const { data, error } = await supabase
    .from('connection_overview')
    .select('*')
    .order('last_message_at', { ascending: false, nullsFirst: false })
    .order('created_at', { ascending: false })

  if (error) throw error
  return data ?? []
}

/**
 * One conversation, for the chat screen, by the other person's username. The
 * view only holds the caller's own connections and there is one per pair, so
 * a username identifies at most one row; RLS returns nothing for a stranger.
 */
export async function getConnectionWith(username: string): Promise<ConnectionOverview | null> {
  const supabase = await createClient()

  const { data } = await supabase
    .from('connection_overview')
    .select('*')
    .eq('other_username', username)
    .maybeSingle()

  return data
}

export async function getMessages(connectionId: string, limit = 50): Promise<Message[]> {
  const supabase = await createClient()

  // RLS (app.can_read_messages) returns nothing unless the caller is a
  // participant of an accepted connection, so an unknown id simply yields [].
  const { data, error } = await supabase
    .from('messages')
    .select('*')
    .eq('connection_id', connectionId)
    .order('created_at', { ascending: false })
    .limit(limit)

  if (error) throw error
  return (data ?? []).reverse()
}
